### ISSUE TITLE
Paragraphs: replace .nonindent with .no-indent in EPUB exporter, or use .first-paragraph

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks-book#324]

**Comment by greatislander** [comment]
Ah yeah, so for EPUB there's a CSS class that's added to any paragraph that doesn't follow another paragraph to keep it from being indented. The class is `.nonindent`, which is (to quote a former colleague) gross: https://github.com/pressbooks/pressbooks/blob/3217c734b9f3d25d840c247a5ac5b16b6c1698cb/inc/modules/export/epub/templates/epub201/mobi-hacks.xsl#L82

The idea here was to change it to a more intuitive class, or ideally find some way of styling these paragraphs without adding classes as part of the export routine. Would be worth testing whether EPUB can handle something like this now:

```css
p {
  text-indent: 0; /* Don't indent paragraphs in general. */
}

p + p {
  text-indent: 2em; /* DO indent paragraphs which immediately follow other paragraphs. */
}
```
